[book]
authors = ["kleines Filmr√∂llchen"]
language = "en"
src = "src"
title = "SOF Programming Language Documentation"

[output.html]
additional-css = ["reference.css"]

[preprocessor.spec]
command = "mdbook-spec"
